// Local type extensions for Email Campaign scheduling
// These types mirror the backend data model added in the backend upgrade.

export interface EmailCampaign {
  id: bigint;
  subject: string;
  body: string;
  recipients: string[];
  scheduledDate: bigint | null;
  status: string; // "Draft" | "Scheduled" | "Sending" | "Sent" | "Failed"
  createdAt: bigint;
  sentAt: bigint | null;
}

// Augment the backendInterface with new email campaign methods.
// The actual runtime bindings are already generated by bindgen;
// this module just provides the TypeScript types for safe casting.
export interface EmailCampaignMethods {
  createEmailCampaign(
    adminEmail: string,
    subject: string,
    body: string,
    recipients: string[],
    scheduledDate: bigint | null,
  ): Promise<bigint>;
  updateEmailCampaign(
    adminEmail: string,
    campaignId: bigint,
    subject: string,
    body: string,
    recipients: string[],
    scheduledDate: bigint | null,
  ): Promise<boolean>;
  getAllEmailCampaigns(adminEmail: string): Promise<EmailCampaign[]>;
  rescheduleEmailCampaign(
    adminEmail: string,
    campaignId: bigint,
    newScheduledDate: bigint,
  ): Promise<boolean>;
  cancelEmailCampaign(adminEmail: string, campaignId: bigint): Promise<boolean>;
  sendNowEmailCampaign(
    adminEmail: string,
    campaignId: bigint,
  ): Promise<boolean>;
}
