/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Build = IDL.Record({
  'id' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'clientName' : IDL.Text,
  'description' : IDL.Text,
  'addedAt' : IDL.Int,
  'category' : IDL.Text,
  'siteUrl' : IDL.Text,
});
export const MarqueeLogo = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'logoUrl' : IDL.Text,
  'addedAt' : IDL.Int,
  'logoLabel' : IDL.Text,
});
export const ReviewId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UpsertResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
  'okAlreadyAdvanced' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const BlogPostId = IDL.Nat;
export const QuestionnaireId = IDL.Nat;
export const AdHocInvoice = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'clientId' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'invoiceNumber' : IDL.Text,
  'stripeSessionId' : IDL.Text,
  'amount' : IDL.Float64,
  'paidAt' : IDL.Opt(IDL.Int),
});
export const ActivityId = IDL.Nat;
export const Status = IDL.Variant({
  'depositReceived' : IDL.Null,
  'cancelled' : IDL.Null,
  'draftReady' : IDL.Null,
  'questionnaireComplete' : IDL.Null,
  'live' : IDL.Null,
  'buildInProgress' : IDL.Null,
  'revisionsInProgress' : IDL.Null,
  'questionnairePending' : IDL.Null,
  'launching' : IDL.Null,
  'paused' : IDL.Null,
  'depositSent' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const OrderId = IDL.Nat;
export const ClientId = IDL.Principal;
export const ActivityLog = IDL.Record({
  'id' : ActivityId,
  'status_at_time' : Status,
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'order_id' : OrderId,
  'client_id' : ClientId,
});
export const UserProfile = IDL.Record({
  'role' : IDL.Text,
  'businessName' : IDL.Text,
  'businessType' : IDL.Text,
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'passwordHash' : IDL.Vec(IDL.Nat8),
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : Status,
  'updated_at' : Timestamp,
  'delivery_window' : IDL.Text,
  'created_at' : Timestamp,
  'launch_target' : IDL.Text,
  'client_id' : ClientId,
  'amount' : IDL.Float64,
  'tier_code' : IDL.Text,
});
export const Questionnaire = IDL.Record({
  'id' : QuestionnaireId,
  'updated_at' : Timestamp,
  'submitted' : IDL.Bool,
  'answers' : IDL.Text,
  'reviewed_at' : IDL.Opt(Timestamp),
  'created_at' : Timestamp,
  'progress' : IDL.Nat,
  'order_id' : OrderId,
  'reviewed' : IDL.Bool,
  'client_id' : ClientId,
  'submitted_at' : IDL.Opt(Timestamp),
  'tier_code' : IDL.Text,
});
export const BillingId = IDL.Nat;
export const SubscriptionId = IDL.Nat;
export const BillingHistory = IDL.Record({
  'id' : BillingId,
  'status' : IDL.Text,
  'payment_date' : Timestamp,
  'subscription_id' : SubscriptionId,
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'stripe_payment_intent_id' : IDL.Text,
  'client_id' : ClientId,
  'amount' : IDL.Float64,
});
export const AdminNotification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'notifType' : IDL.Text,
  'read' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const AdminStats = IDL.Record({
  'outstandingInvoices' : IDL.Nat,
  'activeProjects' : IDL.Nat,
  'totalClients' : IDL.Nat,
  'unreviewedQuestionnaires' : IDL.Nat,
});
export const BlogPost = IDL.Record({
  'id' : BlogPostId,
  'seoMetaKeywords' : IDL.Opt(IDL.Text),
  'status' : IDL.Text,
  'title' : IDL.Text,
  'updated_at' : Timestamp,
  'body' : IDL.Text,
  'slug' : IDL.Text,
  'published_at' : IDL.Opt(Timestamp),
  'created_at' : Timestamp,
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
  'seoMetaDescription' : IDL.Opt(IDL.Text),
  'featured_image_url' : IDL.Opt(IDL.Text),
  'featuredImageCaption' : IDL.Text,
});
export const EmailCampaignId = IDL.Nat;
export const EmailCampaign = IDL.Record({
  'id' : EmailCampaignId,
  'status' : IDL.Text,
  'subject' : IDL.Text,
  'scheduledDate' : IDL.Opt(IDL.Int),
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'sentAt' : IDL.Opt(IDL.Int),
  'recipients' : IDL.Vec(IDL.Text),
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Text,
  'seoMetaKeywords' : IDL.Opt(IDL.Text),
  'client_name' : IDL.Text,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'site_url' : IDL.Text,
  'thumbnail_url' : IDL.Text,
  'imageCaption' : IDL.Text,
  'is_featured' : IDL.Bool,
  'seoMetaDescription' : IDL.Opt(IDL.Text),
  'tier_code' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'proofPoints' : IDL.Opt(IDL.Text),
  'show_questionnaire' : IDL.Bool,
  'seoMetaTitle' : IDL.Opt(IDL.Text),
  'faqItems' : IDL.Opt(IDL.Text),
  'active' : IDL.Bool,
  'payment_type' : IDL.Text,
  'price_monthly' : IDL.Opt(IDL.Float64),
  'speedy_filter' : IDL.Opt(IDL.Text),
  'tagline' : IDL.Opt(IDL.Text),
  'plan_section' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'closingCTA' : IDL.Opt(IDL.Text),
  'bodySections' : IDL.Opt(IDL.Text),
  'upgradePath' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'product_type' : IDL.Text,
  'recommendedPlan' : IDL.Opt(IDL.Text),
  'heroSubheadline' : IDL.Opt(IDL.Text),
  'detailDescription' : IDL.Opt(IDL.Text),
  'seoMetaDescription' : IDL.Opt(IDL.Text),
  'featureBullets' : IDL.Vec(IDL.Text),
  'heroHeadline' : IDL.Opt(IDL.Text),
  'bestFor' : IDL.Opt(IDL.Text),
  'video_url_1' : IDL.Text,
  'video_url_2' : IDL.Text,
  'price_onetime' : IDL.Opt(IDL.Float64),
  'tier_code' : IDL.Opt(IDL.Text),
  'price_annual' : IDL.Opt(IDL.Float64),
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'status' : IDL.Text,
  'clientName' : IDL.Text,
  'clientEmail' : IDL.Text,
  'submittedAt' : IDL.Int,
  'reviewText' : IDL.Text,
  'jobTitle' : IDL.Text,
  'rating' : IDL.Nat,
});
export const DaySchedule = IDL.Record({
  'endHour' : IDL.Nat,
  'isOpen' : IDL.Bool,
  'startHour' : IDL.Nat,
});
export const WeeklySchedule = IDL.Record({
  'tuesday' : DaySchedule,
  'wednesday' : DaySchedule,
  'saturday' : DaySchedule,
  'thursday' : DaySchedule,
  'sunday' : DaySchedule,
  'friday' : DaySchedule,
  'monday' : DaySchedule,
});
export const AvailabilitySettings = IDL.Record({
  'timezone' : IDL.Opt(IDL.Text),
  'blockedDates' : IDL.Vec(IDL.Text),
  'weeklySchedule' : WeeklySchedule,
});
export const BusinessMetrics = IDL.Record({
  'activeBookings' : IDL.Nat,
  'saasPlanStatus' : IDL.Text,
  'monthlyRevenueCents' : IDL.Nat,
});
export const SiteLinkEntry = IDL.Record({
  'url' : IDL.Text,
  'sentAt' : IDL.Int,
});
export const CrmClient = IDL.Record({
  'id' : IDL.Text,
  'webhookSecret' : IDL.Opt(IDL.Text),
  'hasAccount' : IDL.Bool,
  'deletionRequested' : IDL.Bool,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'milestoneUpdatedAt' : IDL.Opt(IDL.Int),
  'onboardingBriefId' : IDL.Opt(IDL.Text),
  'created_at' : IDL.Int,
  'briefSubmittedAt' : IDL.Opt(IDL.Int),
  'email' : IDL.Text,
  'connectedAt' : IDL.Opt(IDL.Int),
  'stripeConnectAccountId' : IDL.Opt(IDL.Text),
  'notes' : IDL.Text,
  'currentMilestone' : IDL.Nat,
  'platformFeePercentage' : IDL.Float64,
  'projectStatus' : IDL.Text,
  'deletionRequestedAt' : IDL.Int,
  'phone' : IDL.Text,
  'stripeConnectStatus' : IDL.Text,
  'lastActivityAt' : IDL.Opt(IDL.Int),
  'briefStatus' : IDL.Opt(IDL.Text),
  'siteLinkLog' : IDL.Vec(SiteLinkEntry),
  'completionPaymentCharged' : IDL.Bool,
  'activeServices' : IDL.Vec(IDL.Text),
});
export const InvoiceId = IDL.Nat;
export const Invoice = IDL.Record({
  'id' : InvoiceId,
  'status' : IDL.Text,
  'updated_at' : Timestamp,
  'invoice_number' : IDL.Text,
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'stripe_payment_intent_id' : IDL.Text,
  'due_date' : Timestamp,
  'paid_at' : IDL.Opt(Timestamp),
  'order_id' : IDL.Opt(OrderId),
  'client_id' : ClientId,
  'amount' : IDL.Float64,
});
export const PurchaseRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'clientEmail' : IDL.Text,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'checkoutUrl' : IDL.Opt(IDL.Text),
  'frequency' : IDL.Text,
  'amount' : IDL.Float64,
  'declineReason' : IDL.Opt(IDL.Text),
  'respondedAt' : IDL.Opt(IDL.Int),
  'requestedAt' : IDL.Int,
});
export const DashboardMetrics = IDL.Record({
  'totalProducts' : IDL.Nat,
  'ordersByStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalOrders' : IDL.Nat,
  'totalOrderValue' : IDL.Nat,
  'outstandingInvoices' : IDL.Nat,
  'recentActivity' : IDL.Vec(IDL.Text),
  'totalClients' : IDL.Nat,
  'unreviewedQuestionnaires' : IDL.Nat,
  'totalActiveSubscriptions' : IDL.Nat,
  'totalWebsites' : IDL.Nat,
});
export const EmailLog = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'templateName' : IDL.Text,
  'timestamp' : IDL.Int,
  'recipientEmail' : IDL.Text,
});
export const EmailTemplateId = IDL.Nat;
export const EmailTemplate = IDL.Record({
  'id' : EmailTemplateId,
  'updated_at' : Timestamp,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'trigger_key' : IDL.Text,
});
export const ClientFileMetadata = IDL.Record({
  'id' : IDL.Text,
  'objectKey' : IDL.Text,
  'clientEmail' : IDL.Text,
  'fileName' : IDL.Text,
  'fileLabel' : IDL.Text,
  'uploaderEmail' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const FleetCanister = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'created_at' : Timestamp,
});
export const GoogleCalendarConfig = IDL.Record({
  'scriptUrl' : IDL.Text,
  'calendarId' : IDL.Text,
  'titleTemplate' : IDL.Text,
  'defaultDurationMinutes' : IDL.Nat,
});
export const GoogleSheetsConfig = IDL.Record({
  'scriptUrl' : IDL.Text,
  'sheetId' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'meetLink' : IDL.Text,
  'rescheduleToken' : IDL.Text,
  'convertedAt' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'path' : IDL.Text,
  'rescheduleHistory' : IDL.Vec(IDL.Int),
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'isDraft' : IDL.Bool,
  'message' : IDL.Text,
  'business' : IDL.Text,
  'meetingMethod' : IDL.Text,
  'rescheduleLinkSentAt' : IDL.Opt(IDL.Int),
});
export const ClientMessage = IDL.Record({
  'id' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'receiverEmail' : IDL.Text,
  'senderName' : IDL.Text,
  'senderEmail' : IDL.Text,
});
export const EditRequestId = IDL.Nat;
export const EditRequest = IDL.Record({
  'id' : EditRequestId,
  'status' : IDL.Text,
  'request_type' : IDL.Text,
  'updated_at' : Timestamp,
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'page_or_section' : IDL.Text,
  'request_number' : IDL.Text,
  'order_id' : IDL.Opt(OrderId),
  'client_id' : ClientId,
  'attachment_url' : IDL.Opt(IDL.Text),
});
export const Subscription = IDL.Record({
  'id' : SubscriptionId,
  'status' : IDL.Text,
  'nextBillingDate' : IDL.Int,
  'updated_at' : Timestamp,
  'plan_code' : IDL.Text,
  'plan_name' : IDL.Text,
  'billing_cycle' : IDL.Text,
  'clientEmail' : IDL.Text,
  'created_at' : Timestamp,
  'stripeCustomerId' : IDL.Opt(IDL.Text),
  'stripe_subscription_id' : IDL.Text,
  'client_id' : ClientId,
  'reminderSentAt' : IDL.Opt(IDL.Int),
  'next_payment_date' : Timestamp,
  'paymentFailed' : IDL.Bool,
});
export const NotificationLogEntry = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'event' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PendingNotification = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const SocialMediaConfig = IDL.Record({
  'instagramUrl' : IDL.Text,
  'youtubeUrl' : IDL.Text,
  'facebookUrl' : IDL.Text,
  'linkedinUrl' : IDL.Text,
  'tiktokUrl' : IDL.Text,
});
export const PushSubscription = IDL.Record({
  'endpoint' : IDL.Text,
  'auth' : IDL.Text,
  'p256dh' : IDL.Text,
});
export const QuestionDefinition = IDL.Record({
  'id' : IDL.Text,
  'inputType' : IDL.Text,
  'questionLabel' : IDL.Text,
  'tierCode' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'description' : IDL.Text,
  'required' : IDL.Bool,
  'placeholder' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const ReferralStat = IDL.Record({
  'successfulConversions' : IDL.Nat,
  'referrerName' : IDL.Text,
  'code' : IDL.Text,
  'referrerEmail' : IDL.Text,
  'totalClicks' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SubAdmin = IDL.Record({
  'allowedTabs' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
});
export const WebhookAuditEntry = IDL.Record({
  'received_at' : IDL.Int,
  'event_id' : IDL.Text,
  'processing_result' : IDL.Text,
  'event_type' : IDL.Text,
});
export const LoginResult = IDL.Variant({
  'ok' : IDL.Record({
    'role' : IDL.Text,
    'email' : IDL.Text,
    'firstName' : IDL.Text,
  }),
  'err' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'activateSubscription' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addBuild' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : Build, 'err' : IDL.Text })],
      [],
    ),
  'addClient' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'addFleetCanister' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addFleetSite' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addFleetSoftware' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addMarqueeLogo' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : MarqueeLogo, 'err' : IDL.Text })],
      [],
    ),
  'addSubAdmin' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateClientProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'approvePurchaseRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'approveReview' : IDL.Func(
      [ReviewId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignMeetingToLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'meetLink' : IDL.Text })],
      [],
    ),
  'blockDate' : IDL.Func([IDL.Text], [], []),
  'cancelEmailCampaign' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'cancelSubscription' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'changePassword' : IDL.Func(
      [
        IDL.Record({
          'email' : IDL.Text,
          'newPasswordHash' : IDL.Vec(IDL.Nat8),
          'currentPasswordHash' : IDL.Vec(IDL.Nat8),
        }),
      ],
      [UpsertResult],
      [],
    ),
  'checkStripeSessionPaid' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'notPaid' : IDL.Null,
          'paid' : IDL.Null,
          'error' : IDL.Text,
        }),
      ],
      [],
    ),
  'clearGoogleCalendarConfig' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'clearGoogleSheetsConfig' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'clearNotificationLog' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'clearPendingPushNotifications' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'convertLeadToClient' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'createAdHocInvoiceSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createBlogPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [UpsertResult],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createCompletionPaymentSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDraftLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'leadId' : IDL.Text })],
      [],
    ),
  'createEditRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [UpsertResult],
      [],
    ),
  'createEmailCampaign' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Int)],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'createLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPortfolioItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : ProductId, 'err' : IDL.Text })],
      [],
    ),
  'createPurchaseRequest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createStripePaymentSession' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createStripePortalSession' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'declinePurchaseRequest' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteBlogPost' : IDL.Func([BlogPostId], [], []),
  'deleteBuild' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteClient' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteClientFile' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteLead' : IDL.Func([IDL.Text], [], []),
  'deleteMarqueeLogo' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deletePortfolioItem' : IDL.Func([IDL.Text], [UpsertResult], []),
  'deleteProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteQuestionnaire' : IDL.Func([QuestionnaireId], [], []),
  'deleteReferral' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteReview' : IDL.Func(
      [ReviewId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'editBuild' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : Build, 'err' : IDL.Text })],
      [],
    ),
  'generateAdminOTP' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'generatePartnerLink' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getAdHocClientInvoices' : IDL.Func([IDL.Text], [IDL.Vec(AdHocInvoice)], []),
  'getAdminAllActivity' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getAdminAllClients' : IDL.Func([], [IDL.Vec(UserProfile)], []),
  'getAdminAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAdminAllQuestionnaires' : IDL.Func(
      [],
      [IDL.Vec(Questionnaire)],
      ['query'],
    ),
  'getAdminBillingHistory' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(BillingHistory), 'err' : IDL.Text })],
      [],
    ),
  'getAdminContactEmail' : IDL.Func([], [IDL.Text], ['query']),
  'getAdminNotifications' : IDL.Func([], [IDL.Vec(AdminNotification)], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllBlogPostsAdmin' : IDL.Func([], [IDL.Vec(BlogPost)], []),
  'getAllEmailCampaigns' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(EmailCampaign), 'err' : IDL.Text })],
      [],
    ),
  'getAllPortfolioAdmin' : IDL.Func([], [IDL.Vec(PortfolioItem)], []),
  'getAllProductsAdmin' : IDL.Func([], [IDL.Vec(Product)], []),
  'getAllSiteText' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAvailability' : IDL.Func([], [AvailabilitySettings], ['query']),
  'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBuilds' : IDL.Func([], [IDL.Vec(Build)], []),
  'getBusinessMetrics' : IDL.Func([], [BusinessMetrics], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterCycles' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'getCategoryVisibility' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getClientBriefStatus' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getClientBusinessMetrics' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : BusinessMetrics, 'err' : IDL.Text })],
      [],
    ),
  'getClientByEmail' : IDL.Func([IDL.Text], [IDL.Opt(CrmClient)], []),
  'getClientByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getClientFileUrl' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getClientInvoices' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Invoice)],
      ['query'],
    ),
  'getClientMilestone' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Opt(IDL.Nat), 'err' : IDL.Text })],
      [],
    ),
  'getClientOrderVolumes' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getClientOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getClientPurchaseRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PurchaseRequest)],
      ['query'],
    ),
  'getClients' : IDL.Func([], [IDL.Vec(CrmClient)], []),
  'getConnectedClients' : IDL.Func([], [IDL.Vec(CrmClient)], ['query']),
  'getConversionStats' : IDL.Func(
      [IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [
        IDL.Record({
          'convertedLeads' : IDL.Nat,
          'totalLeads' : IDL.Nat,
          'conversionRate' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getCountryBreakdown' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64))],
      ['query'],
    ),
  'getCycles' : IDL.Func([], [IDL.Nat], ['query']),
  'getDailyVisitorChart' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
  'getEmailHealth' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalFailures' : IDL.Nat,
          'lastFailureTimestamp' : IDL.Int,
          'last24hFailures' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getEmailLogs' : IDL.Func([], [IDL.Vec(EmailLog)], ['query']),
  'getEmailTemplates' : IDL.Func([], [IDL.Vec(EmailTemplate)], ['query']),
  'getFilesForClient' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ClientFileMetadata)],
      [],
    ),
  'getFleetSites' : IDL.Func([], [IDL.Vec(FleetCanister)], []),
  'getFleetSoftware' : IDL.Func([], [IDL.Vec(FleetCanister)], []),
  'getGlobalTaxRate' : IDL.Func([], [IDL.Float64], ['query']),
  'getGoogleCalendarConfig' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : GoogleCalendarConfig, 'err' : IDL.Text })],
      [],
    ),
  'getGoogleSheetsConfig' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : GoogleSheetsConfig, 'err' : IDL.Text })],
      [],
    ),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getLiveVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getLogoUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getMarqueeLogos' : IDL.Func([], [IDL.Vec(MarqueeLogo)], ['query']),
  'getMessages' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(ClientMessage)], []),
  'getMyActivity' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getMyAdHocInvoices' : IDL.Func([], [IDL.Vec(AdHocInvoice)], ['query']),
  'getMyAdminPermissions' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
      [],
    ),
  'getMyBillingHistory' : IDL.Func([], [IDL.Vec(BillingHistory)], ['query']),
  'getMyEditRequests' : IDL.Func([], [IDL.Vec(EditRequest)], ['query']),
  'getMyInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getMyMostRecentQuestionnaire' : IDL.Func(
      [],
      [IDL.Opt(Questionnaire)],
      ['query'],
    ),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], []),
  'getMyQuestionnaires' : IDL.Func([], [IDL.Vec(Questionnaire)], ['query']),
  'getMyReferralClicks' : IDL.Func([], [IDL.Nat], []),
  'getMyReferralCode' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getMyReferralConversions' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getMyReview' : IDL.Func([IDL.Text], [IDL.Opt(Review)], ['query']),
  'getMySubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getNextAvailableSlot' : IDL.Func(
      [],
      [IDL.Record({ 'date' : IDL.Text, 'time' : IDL.Text })],
      ['query'],
    ),
  'getNotificationLog' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(NotificationLogEntry), 'err' : IDL.Text })],
      [],
    ),
  'getOrCreateMyReferralCode' : IDL.Func([], [IDL.Text], []),
  'getPendingPushNotifications' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(PendingNotification), 'err' : IDL.Text })],
      [],
    ),
  'getPendingReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getPendingSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], []),
  'getPortalShopProductIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getPortalShopProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductImageUrl' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByType' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getPublicAvailability' : IDL.Func([], [AvailabilitySettings], ['query']),
  'getPublicBuilds' : IDL.Func([], [IDL.Vec(Build)], ['query']),
  'getPublicBuildsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPublicSocialMediaConfig' : IDL.Func([], [SocialMediaConfig], ['query']),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getPublishedPortfolio' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getPurchaseRequests' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(PurchaseRequest), 'err' : IDL.Text })],
      [],
    ),
  'getPushSubscription' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Opt(PushSubscription), 'err' : IDL.Text })],
      [],
    ),
  'getQuestionDefinitions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuestionDefinition)],
      ['query'],
    ),
  'getQuestionnaireByClientId' : IDL.Func(
      [ClientId],
      [IDL.Opt(Questionnaire)],
      ['query'],
    ),
  'getReferralStats' : IDL.Func([], [IDL.Vec(ReferralStat)], []),
  'getRejectedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getReminderLeadDays' : IDL.Func([], [IDL.Nat], []),
  'getRescheduleHistory' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Int)], ['query']),
  'getRescheduleLeadByToken' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Record({ 'isExpired' : IDL.Bool, 'lead' : Lead }))],
      ['query'],
    ),
  'getSiteBaseUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getSiteLinkLog' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(SiteLinkEntry), 'err' : IDL.Text })],
      ['query'],
    ),
  'getSiteText' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getSocialMediaConfig' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : SocialMediaConfig, 'err' : IDL.Text })],
      [],
    ),
  'getStripeCharges' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getStripeConfiguration' : IDL.Func(
      [],
      [IDL.Opt(StripeConfiguration)],
      ['query'],
    ),
  'getStripeCustomers' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getStripeDashboardData' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getStripePayouts' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getStripePublishableKey' : IDL.Func([], [IDL.Text], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getStripeSubscriptions' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getStripeTestMode' : IDL.Func([], [IDL.Bool], ['query']),
  'getSubAdmins' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Vec(IDL.Tuple(IDL.Text, SubAdmin)),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'getTopPages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64))],
      ['query'],
    ),
  'getUnreadMessageCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getVapidPublicKey' : IDL.Func([], [IDL.Text], ['query']),
  'getVisitorStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'todayUnique' : IDL.Nat,
          'weekUnique' : IDL.Nat,
          'monthUnique' : IDL.Nat,
          'todaySessions' : IDL.Nat,
          'allTimeUnique' : IDL.Nat,
          'monthSessions' : IDL.Nat,
          'weekSessions' : IDL.Nat,
          'allTimeSessions' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getWebhookAuditLog' : IDL.Func([], [IDL.Vec(WebhookAuditEntry)], []),
  'handleStripeWebhook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'helpRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'initAdminAccount' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isGoogleCalendarConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isGoogleSheetsConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeTestMode' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Record({ 'email' : IDL.Text, 'passwordHash' : IDL.Vec(IDL.Nat8) })],
      [LoginResult],
      [],
    ),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markCompletionPaymentCharged' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'markInvoicePaid' : IDL.Func([IDL.Text, IDL.Text], [UpsertResult], []),
  'markMessagesRead' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'markQuestionnaireReviewed' : IDL.Func([QuestionnaireId], [], []),
  'publishBlogPost' : IDL.Func([BlogPostId], [], []),
  'publishPortfolioItem' : IDL.Func([IDL.Text], [UpsertResult], []),
  'recordVisit' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'registerAdminPrincipal' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'registerUser' : IDL.Func(
      [
        IDL.Record({
          'email' : IDL.Text,
          'passwordHash' : IDL.Vec(IDL.Nat8),
          'lastName' : IDL.Text,
          'firstName' : IDL.Text,
        }),
      ],
      [UpsertResult],
      [],
    ),
  'rejectReview' : IDL.Func(
      [ReviewId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeAdminPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removeFleetCanister' : IDL.Func([IDL.Text], [], []),
  'removeFleetSite' : IDL.Func([IDL.Text], [], []),
  'removeFleetSoftware' : IDL.Func([IDL.Text], [], []),
  'removeProductImage' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removePushSubscription' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'removeSubAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'reorderMarqueeLogos' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'requestAccountDeletion' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'requestPasswordReset' : IDL.Func([IDL.Text], [IDL.Text], []),
  'rescheduleEmailCampaign' : IDL.Func(
      [IDL.Nat, IDL.Int],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'rescheduleLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'reseedCatalog' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'resendEmail' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'resendSiteLink' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resetPasswordWithToken' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Text],
      [],
    ),
  'saveEmailTemplate' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'savePushSubscription' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'sendDepositInvoice' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Nat, IDL.Text, Timestamp],
      [IDL.Text],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ClientMessage, 'err' : IDL.Text })],
      [],
    ),
  'sendNowEmailCampaign' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'sendOrderStatusEmail' : IDL.Func([IDL.Principal, Status, IDL.Text], [], []),
  'sendRescheduleLink' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool })],
      [],
    ),
  'sendSiteLink' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'sendUpcomingBillingReminders' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'setAdminEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setAvailability' : IDL.Func([AvailabilitySettings], [], []),
  'setClientWebhookSecret' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setGlobalTaxRate' : IDL.Func(
      [IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setGoogleCalendarConfig' : IDL.Func(
      [GoogleCalendarConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setGoogleSheetsConfig' : IDL.Func(
      [GoogleSheetsConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setLogoUrl' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setReminderLeadDays' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setSiteAuditFallbackPrice' : IDL.Func(
      [IDL.Int],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setSiteBaseUrl' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setSocialMediaConfig' : IDL.Func(
      [SocialMediaConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setStripePublishableKey' : IDL.Func([IDL.Text], [], []),
  'setStripeSecretKey' : IDL.Func([IDL.Text], [], []),
  'setStripeTestMode' : IDL.Func([IDL.Bool], [], []),
  'setStripeWebhookSecret' : IDL.Func([IDL.Text], [], []),
  'setVapidKeys' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setWebhookSharedSecret' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitCancellationRequest' : IDL.Func([IDL.Text], [UpsertResult], []),
  'submitQuestionnaire' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'submitReview' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ReviewId, 'err' : IDL.Text })],
      [],
    ),
  'togglePortalShopProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'toggleProductStatus' : IDL.Func([IDL.Text], [UpsertResult], []),
  'trackReferralClick' : IDL.Func([IDL.Text], [], []),
  'trackReferralConversion' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unblockDate' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unpublishBlogPost' : IDL.Func([BlogPostId], [], []),
  'unpublishPortfolioItem' : IDL.Func([IDL.Text], [UpsertResult], []),
  'updateBlogPost' : IDL.Func(
      [
        BlogPostId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateCategoryVisibility' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [UpsertResult],
      [],
    ),
  'updateClientBriefStatus' : IDL.Func([IDL.Text], [UpsertResult], []),
  'updateClientHasAccount' : IDL.Func([IDL.Text, IDL.Bool], [UpsertResult], []),
  'updateClientMilestone' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateClientNotes' : IDL.Func([IDL.Text, IDL.Text], [UpsertResult], []),
  'updateClientPlatformFee' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateClientStatus' : IDL.Func([IDL.Text, IDL.Text], [UpsertResult], []),
  'updateClientStripeAccountId' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateEmailCampaign' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Int)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateLeadStatus' : IDL.Func([IDL.Text, IDL.Text], [UpsertResult], []),
  'updateMarqueeLogo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : MarqueeLogo, 'err' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [UpsertResult], []),
  'updatePortfolioItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [UpsertResult],
      [],
    ),
  'updateProductDescription' : IDL.Func(
      [IDL.Text, IDL.Text],
      [UpsertResult],
      [],
    ),
  'updateProductDetailContent' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [UpsertResult],
      [],
    ),
  'updateProductImage' : IDL.Func([IDL.Text, IDL.Text], [UpsertResult], []),
  'updateProductPaymentType' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateProductPlanSection' : IDL.Func(
      [ProductId, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateProductPrice' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
      ],
      [UpsertResult],
      [],
    ),
  'updateProductRichFields' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [UpsertResult],
      [],
    ),
  'updateProductSpeedyFilter' : IDL.Func(
      [ProductId, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateProfile' : IDL.Func(
      [
        IDL.Record({
          'businessName' : IDL.Text,
          'businessType' : IDL.Text,
          'email' : IDL.Text,
          'phone' : IDL.Text,
          'lastName' : IDL.Text,
          'firstName' : IDL.Text,
        }),
      ],
      [UpsertResult],
      [],
    ),
  'updateQuestionDefinitions' : IDL.Func(
      [IDL.Text, IDL.Vec(QuestionDefinition)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateSiteText' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateSubAdminTabs' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'uploadFileToClient' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ClientFileMetadata, 'err' : IDL.Text })],
      [],
    ),
  'verifyAdminOTP' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'verifyAndRecordPurchase' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'verifySession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Build = IDL.Record({
    'id' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'clientName' : IDL.Text,
    'description' : IDL.Text,
    'addedAt' : IDL.Int,
    'category' : IDL.Text,
    'siteUrl' : IDL.Text,
  });
  const MarqueeLogo = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'logoUrl' : IDL.Text,
    'addedAt' : IDL.Int,
    'logoLabel' : IDL.Text,
  });
  const ReviewId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UpsertResult = IDL.Variant({
    'ok' : IDL.Null,
    'err' : IDL.Text,
    'okAlreadyAdvanced' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const BlogPostId = IDL.Nat;
  const QuestionnaireId = IDL.Nat;
  const AdHocInvoice = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'clientId' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'invoiceNumber' : IDL.Text,
    'stripeSessionId' : IDL.Text,
    'amount' : IDL.Float64,
    'paidAt' : IDL.Opt(IDL.Int),
  });
  const ActivityId = IDL.Nat;
  const Status = IDL.Variant({
    'depositReceived' : IDL.Null,
    'cancelled' : IDL.Null,
    'draftReady' : IDL.Null,
    'questionnaireComplete' : IDL.Null,
    'live' : IDL.Null,
    'buildInProgress' : IDL.Null,
    'revisionsInProgress' : IDL.Null,
    'questionnairePending' : IDL.Null,
    'launching' : IDL.Null,
    'paused' : IDL.Null,
    'depositSent' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const OrderId = IDL.Nat;
  const ClientId = IDL.Principal;
  const ActivityLog = IDL.Record({
    'id' : ActivityId,
    'status_at_time' : Status,
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'order_id' : OrderId,
    'client_id' : ClientId,
  });
  const UserProfile = IDL.Record({
    'role' : IDL.Text,
    'businessName' : IDL.Text,
    'businessType' : IDL.Text,
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'passwordHash' : IDL.Vec(IDL.Nat8),
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : Status,
    'updated_at' : Timestamp,
    'delivery_window' : IDL.Text,
    'created_at' : Timestamp,
    'launch_target' : IDL.Text,
    'client_id' : ClientId,
    'amount' : IDL.Float64,
    'tier_code' : IDL.Text,
  });
  const Questionnaire = IDL.Record({
    'id' : QuestionnaireId,
    'updated_at' : Timestamp,
    'submitted' : IDL.Bool,
    'answers' : IDL.Text,
    'reviewed_at' : IDL.Opt(Timestamp),
    'created_at' : Timestamp,
    'progress' : IDL.Nat,
    'order_id' : OrderId,
    'reviewed' : IDL.Bool,
    'client_id' : ClientId,
    'submitted_at' : IDL.Opt(Timestamp),
    'tier_code' : IDL.Text,
  });
  const BillingId = IDL.Nat;
  const SubscriptionId = IDL.Nat;
  const BillingHistory = IDL.Record({
    'id' : BillingId,
    'status' : IDL.Text,
    'payment_date' : Timestamp,
    'subscription_id' : SubscriptionId,
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'stripe_payment_intent_id' : IDL.Text,
    'client_id' : ClientId,
    'amount' : IDL.Float64,
  });
  const AdminNotification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'notifType' : IDL.Text,
    'read' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const AdminStats = IDL.Record({
    'outstandingInvoices' : IDL.Nat,
    'activeProjects' : IDL.Nat,
    'totalClients' : IDL.Nat,
    'unreviewedQuestionnaires' : IDL.Nat,
  });
  const BlogPost = IDL.Record({
    'id' : BlogPostId,
    'seoMetaKeywords' : IDL.Opt(IDL.Text),
    'status' : IDL.Text,
    'title' : IDL.Text,
    'updated_at' : Timestamp,
    'body' : IDL.Text,
    'slug' : IDL.Text,
    'published_at' : IDL.Opt(Timestamp),
    'created_at' : Timestamp,
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
    'seoMetaDescription' : IDL.Opt(IDL.Text),
    'featured_image_url' : IDL.Opt(IDL.Text),
    'featuredImageCaption' : IDL.Text,
  });
  const EmailCampaignId = IDL.Nat;
  const EmailCampaign = IDL.Record({
    'id' : EmailCampaignId,
    'status' : IDL.Text,
    'subject' : IDL.Text,
    'scheduledDate' : IDL.Opt(IDL.Int),
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'sentAt' : IDL.Opt(IDL.Int),
    'recipients' : IDL.Vec(IDL.Text),
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Text,
    'seoMetaKeywords' : IDL.Opt(IDL.Text),
    'client_name' : IDL.Text,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'site_url' : IDL.Text,
    'thumbnail_url' : IDL.Text,
    'imageCaption' : IDL.Text,
    'is_featured' : IDL.Bool,
    'seoMetaDescription' : IDL.Opt(IDL.Text),
    'tier_code' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'proofPoints' : IDL.Opt(IDL.Text),
    'show_questionnaire' : IDL.Bool,
    'seoMetaTitle' : IDL.Opt(IDL.Text),
    'faqItems' : IDL.Opt(IDL.Text),
    'active' : IDL.Bool,
    'payment_type' : IDL.Text,
    'price_monthly' : IDL.Opt(IDL.Float64),
    'speedy_filter' : IDL.Opt(IDL.Text),
    'tagline' : IDL.Opt(IDL.Text),
    'plan_section' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'closingCTA' : IDL.Opt(IDL.Text),
    'bodySections' : IDL.Opt(IDL.Text),
    'upgradePath' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'product_type' : IDL.Text,
    'recommendedPlan' : IDL.Opt(IDL.Text),
    'heroSubheadline' : IDL.Opt(IDL.Text),
    'detailDescription' : IDL.Opt(IDL.Text),
    'seoMetaDescription' : IDL.Opt(IDL.Text),
    'featureBullets' : IDL.Vec(IDL.Text),
    'heroHeadline' : IDL.Opt(IDL.Text),
    'bestFor' : IDL.Opt(IDL.Text),
    'video_url_1' : IDL.Text,
    'video_url_2' : IDL.Text,
    'price_onetime' : IDL.Opt(IDL.Float64),
    'tier_code' : IDL.Opt(IDL.Text),
    'price_annual' : IDL.Opt(IDL.Float64),
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'status' : IDL.Text,
    'clientName' : IDL.Text,
    'clientEmail' : IDL.Text,
    'submittedAt' : IDL.Int,
    'reviewText' : IDL.Text,
    'jobTitle' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const DaySchedule = IDL.Record({
    'endHour' : IDL.Nat,
    'isOpen' : IDL.Bool,
    'startHour' : IDL.Nat,
  });
  const WeeklySchedule = IDL.Record({
    'tuesday' : DaySchedule,
    'wednesday' : DaySchedule,
    'saturday' : DaySchedule,
    'thursday' : DaySchedule,
    'sunday' : DaySchedule,
    'friday' : DaySchedule,
    'monday' : DaySchedule,
  });
  const AvailabilitySettings = IDL.Record({
    'timezone' : IDL.Opt(IDL.Text),
    'blockedDates' : IDL.Vec(IDL.Text),
    'weeklySchedule' : WeeklySchedule,
  });
  const BusinessMetrics = IDL.Record({
    'activeBookings' : IDL.Nat,
    'saasPlanStatus' : IDL.Text,
    'monthlyRevenueCents' : IDL.Nat,
  });
  const SiteLinkEntry = IDL.Record({ 'url' : IDL.Text, 'sentAt' : IDL.Int });
  const CrmClient = IDL.Record({
    'id' : IDL.Text,
    'webhookSecret' : IDL.Opt(IDL.Text),
    'hasAccount' : IDL.Bool,
    'deletionRequested' : IDL.Bool,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'milestoneUpdatedAt' : IDL.Opt(IDL.Int),
    'onboardingBriefId' : IDL.Opt(IDL.Text),
    'created_at' : IDL.Int,
    'briefSubmittedAt' : IDL.Opt(IDL.Int),
    'email' : IDL.Text,
    'connectedAt' : IDL.Opt(IDL.Int),
    'stripeConnectAccountId' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'currentMilestone' : IDL.Nat,
    'platformFeePercentage' : IDL.Float64,
    'projectStatus' : IDL.Text,
    'deletionRequestedAt' : IDL.Int,
    'phone' : IDL.Text,
    'stripeConnectStatus' : IDL.Text,
    'lastActivityAt' : IDL.Opt(IDL.Int),
    'briefStatus' : IDL.Opt(IDL.Text),
    'siteLinkLog' : IDL.Vec(SiteLinkEntry),
    'completionPaymentCharged' : IDL.Bool,
    'activeServices' : IDL.Vec(IDL.Text),
  });
  const InvoiceId = IDL.Nat;
  const Invoice = IDL.Record({
    'id' : InvoiceId,
    'status' : IDL.Text,
    'updated_at' : Timestamp,
    'invoice_number' : IDL.Text,
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'stripe_payment_intent_id' : IDL.Text,
    'due_date' : Timestamp,
    'paid_at' : IDL.Opt(Timestamp),
    'order_id' : IDL.Opt(OrderId),
    'client_id' : ClientId,
    'amount' : IDL.Float64,
  });
  const PurchaseRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'clientEmail' : IDL.Text,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'checkoutUrl' : IDL.Opt(IDL.Text),
    'frequency' : IDL.Text,
    'amount' : IDL.Float64,
    'declineReason' : IDL.Opt(IDL.Text),
    'respondedAt' : IDL.Opt(IDL.Int),
    'requestedAt' : IDL.Int,
  });
  const DashboardMetrics = IDL.Record({
    'totalProducts' : IDL.Nat,
    'ordersByStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalOrders' : IDL.Nat,
    'totalOrderValue' : IDL.Nat,
    'outstandingInvoices' : IDL.Nat,
    'recentActivity' : IDL.Vec(IDL.Text),
    'totalClients' : IDL.Nat,
    'unreviewedQuestionnaires' : IDL.Nat,
    'totalActiveSubscriptions' : IDL.Nat,
    'totalWebsites' : IDL.Nat,
  });
  const EmailLog = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'templateName' : IDL.Text,
    'timestamp' : IDL.Int,
    'recipientEmail' : IDL.Text,
  });
  const EmailTemplateId = IDL.Nat;
  const EmailTemplate = IDL.Record({
    'id' : EmailTemplateId,
    'updated_at' : Timestamp,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'trigger_key' : IDL.Text,
  });
  const ClientFileMetadata = IDL.Record({
    'id' : IDL.Text,
    'objectKey' : IDL.Text,
    'clientEmail' : IDL.Text,
    'fileName' : IDL.Text,
    'fileLabel' : IDL.Text,
    'uploaderEmail' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const FleetCanister = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'created_at' : Timestamp,
  });
  const GoogleCalendarConfig = IDL.Record({
    'scriptUrl' : IDL.Text,
    'calendarId' : IDL.Text,
    'titleTemplate' : IDL.Text,
    'defaultDurationMinutes' : IDL.Nat,
  });
  const GoogleSheetsConfig = IDL.Record({
    'scriptUrl' : IDL.Text,
    'sheetId' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'meetLink' : IDL.Text,
    'rescheduleToken' : IDL.Text,
    'convertedAt' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'path' : IDL.Text,
    'rescheduleHistory' : IDL.Vec(IDL.Int),
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'isDraft' : IDL.Bool,
    'message' : IDL.Text,
    'business' : IDL.Text,
    'meetingMethod' : IDL.Text,
    'rescheduleLinkSentAt' : IDL.Opt(IDL.Int),
  });
  const ClientMessage = IDL.Record({
    'id' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'receiverEmail' : IDL.Text,
    'senderName' : IDL.Text,
    'senderEmail' : IDL.Text,
  });
  const EditRequestId = IDL.Nat;
  const EditRequest = IDL.Record({
    'id' : EditRequestId,
    'status' : IDL.Text,
    'request_type' : IDL.Text,
    'updated_at' : Timestamp,
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'page_or_section' : IDL.Text,
    'request_number' : IDL.Text,
    'order_id' : IDL.Opt(OrderId),
    'client_id' : ClientId,
    'attachment_url' : IDL.Opt(IDL.Text),
  });
  const Subscription = IDL.Record({
    'id' : SubscriptionId,
    'status' : IDL.Text,
    'nextBillingDate' : IDL.Int,
    'updated_at' : Timestamp,
    'plan_code' : IDL.Text,
    'plan_name' : IDL.Text,
    'billing_cycle' : IDL.Text,
    'clientEmail' : IDL.Text,
    'created_at' : Timestamp,
    'stripeCustomerId' : IDL.Opt(IDL.Text),
    'stripe_subscription_id' : IDL.Text,
    'client_id' : ClientId,
    'reminderSentAt' : IDL.Opt(IDL.Int),
    'next_payment_date' : Timestamp,
    'paymentFailed' : IDL.Bool,
  });
  const NotificationLogEntry = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'event' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PendingNotification = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const SocialMediaConfig = IDL.Record({
    'instagramUrl' : IDL.Text,
    'youtubeUrl' : IDL.Text,
    'facebookUrl' : IDL.Text,
    'linkedinUrl' : IDL.Text,
    'tiktokUrl' : IDL.Text,
  });
  const PushSubscription = IDL.Record({
    'endpoint' : IDL.Text,
    'auth' : IDL.Text,
    'p256dh' : IDL.Text,
  });
  const QuestionDefinition = IDL.Record({
    'id' : IDL.Text,
    'inputType' : IDL.Text,
    'questionLabel' : IDL.Text,
    'tierCode' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'description' : IDL.Text,
    'required' : IDL.Bool,
    'placeholder' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const ReferralStat = IDL.Record({
    'successfulConversions' : IDL.Nat,
    'referrerName' : IDL.Text,
    'code' : IDL.Text,
    'referrerEmail' : IDL.Text,
    'totalClicks' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SubAdmin = IDL.Record({
    'allowedTabs' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const WebhookAuditEntry = IDL.Record({
    'received_at' : IDL.Int,
    'event_id' : IDL.Text,
    'processing_result' : IDL.Text,
    'event_type' : IDL.Text,
  });
  const LoginResult = IDL.Variant({
    'ok' : IDL.Record({
      'role' : IDL.Text,
      'email' : IDL.Text,
      'firstName' : IDL.Text,
    }),
    'err' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'activateSubscription' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addBuild' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : Build, 'err' : IDL.Text })],
        [],
      ),
    'addClient' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'addFleetCanister' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addFleetSite' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addFleetSoftware' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addMarqueeLogo' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : MarqueeLogo, 'err' : IDL.Text })],
        [],
      ),
    'addSubAdmin' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateClientProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'approvePurchaseRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'approveReview' : IDL.Func(
        [ReviewId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignMeetingToLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'meetLink' : IDL.Text })],
        [],
      ),
    'blockDate' : IDL.Func([IDL.Text], [], []),
    'cancelEmailCampaign' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'cancelSubscription' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'changePassword' : IDL.Func(
        [
          IDL.Record({
            'email' : IDL.Text,
            'newPasswordHash' : IDL.Vec(IDL.Nat8),
            'currentPasswordHash' : IDL.Vec(IDL.Nat8),
          }),
        ],
        [UpsertResult],
        [],
      ),
    'checkStripeSessionPaid' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'notPaid' : IDL.Null,
            'paid' : IDL.Null,
            'error' : IDL.Text,
          }),
        ],
        [],
      ),
    'clearGoogleCalendarConfig' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'clearGoogleSheetsConfig' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'clearNotificationLog' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'clearPendingPushNotifications' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'convertLeadToClient' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'createAdHocInvoiceSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createBlogPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [UpsertResult],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createCompletionPaymentSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDraftLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'leadId' : IDL.Text })],
        [],
      ),
    'createEditRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [UpsertResult],
        [],
      ),
    'createEmailCampaign' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Int)],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'createLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPortfolioItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : ProductId, 'err' : IDL.Text })],
        [],
      ),
    'createPurchaseRequest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createStripePaymentSession' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createStripePortalSession' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'declinePurchaseRequest' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteBlogPost' : IDL.Func([BlogPostId], [], []),
    'deleteBuild' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteClient' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteClientFile' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteLead' : IDL.Func([IDL.Text], [], []),
    'deleteMarqueeLogo' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deletePortfolioItem' : IDL.Func([IDL.Text], [UpsertResult], []),
    'deleteProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteQuestionnaire' : IDL.Func([QuestionnaireId], [], []),
    'deleteReferral' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteReview' : IDL.Func(
        [ReviewId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'editBuild' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : Build, 'err' : IDL.Text })],
        [],
      ),
    'generateAdminOTP' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'generatePartnerLink' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getAdHocClientInvoices' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AdHocInvoice)],
        [],
      ),
    'getAdminAllActivity' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getAdminAllClients' : IDL.Func([], [IDL.Vec(UserProfile)], []),
    'getAdminAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAdminAllQuestionnaires' : IDL.Func(
        [],
        [IDL.Vec(Questionnaire)],
        ['query'],
      ),
    'getAdminBillingHistory' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(BillingHistory), 'err' : IDL.Text })],
        [],
      ),
    'getAdminContactEmail' : IDL.Func([], [IDL.Text], ['query']),
    'getAdminNotifications' : IDL.Func([], [IDL.Vec(AdminNotification)], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllBlogPostsAdmin' : IDL.Func([], [IDL.Vec(BlogPost)], []),
    'getAllEmailCampaigns' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(EmailCampaign), 'err' : IDL.Text })],
        [],
      ),
    'getAllPortfolioAdmin' : IDL.Func([], [IDL.Vec(PortfolioItem)], []),
    'getAllProductsAdmin' : IDL.Func([], [IDL.Vec(Product)], []),
    'getAllSiteText' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAvailability' : IDL.Func([], [AvailabilitySettings], ['query']),
    'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBuilds' : IDL.Func([], [IDL.Vec(Build)], []),
    'getBusinessMetrics' : IDL.Func([], [BusinessMetrics], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterCycles' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'getCategoryVisibility' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getClientBriefStatus' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getClientBusinessMetrics' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : BusinessMetrics, 'err' : IDL.Text })],
        [],
      ),
    'getClientByEmail' : IDL.Func([IDL.Text], [IDL.Opt(CrmClient)], []),
    'getClientByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getClientFileUrl' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getClientInvoices' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getClientMilestone' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Opt(IDL.Nat), 'err' : IDL.Text })],
        [],
      ),
    'getClientOrderVolumes' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getClientOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getClientPurchaseRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PurchaseRequest)],
        ['query'],
      ),
    'getClients' : IDL.Func([], [IDL.Vec(CrmClient)], []),
    'getConnectedClients' : IDL.Func([], [IDL.Vec(CrmClient)], ['query']),
    'getConversionStats' : IDL.Func(
        [IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [
          IDL.Record({
            'convertedLeads' : IDL.Nat,
            'totalLeads' : IDL.Nat,
            'conversionRate' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getCountryBreakdown' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64))],
        ['query'],
      ),
    'getCycles' : IDL.Func([], [IDL.Nat], ['query']),
    'getDailyVisitorChart' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
    'getEmailHealth' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalFailures' : IDL.Nat,
            'lastFailureTimestamp' : IDL.Int,
            'last24hFailures' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getEmailLogs' : IDL.Func([], [IDL.Vec(EmailLog)], ['query']),
    'getEmailTemplates' : IDL.Func([], [IDL.Vec(EmailTemplate)], ['query']),
    'getFilesForClient' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ClientFileMetadata)],
        [],
      ),
    'getFleetSites' : IDL.Func([], [IDL.Vec(FleetCanister)], []),
    'getFleetSoftware' : IDL.Func([], [IDL.Vec(FleetCanister)], []),
    'getGlobalTaxRate' : IDL.Func([], [IDL.Float64], ['query']),
    'getGoogleCalendarConfig' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : GoogleCalendarConfig, 'err' : IDL.Text })],
        [],
      ),
    'getGoogleSheetsConfig' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : GoogleSheetsConfig, 'err' : IDL.Text })],
        [],
      ),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getLiveVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getLogoUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getMarqueeLogos' : IDL.Func([], [IDL.Vec(MarqueeLogo)], ['query']),
    'getMessages' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ClientMessage)],
        [],
      ),
    'getMyActivity' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getMyAdHocInvoices' : IDL.Func([], [IDL.Vec(AdHocInvoice)], ['query']),
    'getMyAdminPermissions' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Text), 'err' : IDL.Text })],
        [],
      ),
    'getMyBillingHistory' : IDL.Func([], [IDL.Vec(BillingHistory)], ['query']),
    'getMyEditRequests' : IDL.Func([], [IDL.Vec(EditRequest)], ['query']),
    'getMyInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getMyMostRecentQuestionnaire' : IDL.Func(
        [],
        [IDL.Opt(Questionnaire)],
        ['query'],
      ),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], []),
    'getMyQuestionnaires' : IDL.Func([], [IDL.Vec(Questionnaire)], ['query']),
    'getMyReferralClicks' : IDL.Func([], [IDL.Nat], []),
    'getMyReferralCode' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getMyReferralConversions' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getMyReview' : IDL.Func([IDL.Text], [IDL.Opt(Review)], ['query']),
    'getMySubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getNextAvailableSlot' : IDL.Func(
        [],
        [IDL.Record({ 'date' : IDL.Text, 'time' : IDL.Text })],
        ['query'],
      ),
    'getNotificationLog' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Vec(NotificationLogEntry),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getOrCreateMyReferralCode' : IDL.Func([], [IDL.Text], []),
    'getPendingPushNotifications' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Vec(PendingNotification),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getPendingReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getPendingSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], []),
    'getPortalShopProductIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getPortalShopProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductImageUrl' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByType' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getPublicAvailability' : IDL.Func([], [AvailabilitySettings], ['query']),
    'getPublicBuilds' : IDL.Func([], [IDL.Vec(Build)], ['query']),
    'getPublicBuildsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPublicSocialMediaConfig' : IDL.Func([], [SocialMediaConfig], ['query']),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getPublishedPortfolio' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getPurchaseRequests' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(PurchaseRequest), 'err' : IDL.Text })],
        [],
      ),
    'getPushSubscription' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Opt(PushSubscription), 'err' : IDL.Text })],
        [],
      ),
    'getQuestionDefinitions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuestionDefinition)],
        ['query'],
      ),
    'getQuestionnaireByClientId' : IDL.Func(
        [ClientId],
        [IDL.Opt(Questionnaire)],
        ['query'],
      ),
    'getReferralStats' : IDL.Func([], [IDL.Vec(ReferralStat)], []),
    'getRejectedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getReminderLeadDays' : IDL.Func([], [IDL.Nat], []),
    'getRescheduleHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Int)],
        ['query'],
      ),
    'getRescheduleLeadByToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Record({ 'isExpired' : IDL.Bool, 'lead' : Lead }))],
        ['query'],
      ),
    'getSiteBaseUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getSiteLinkLog' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(SiteLinkEntry), 'err' : IDL.Text })],
        ['query'],
      ),
    'getSiteText' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getSocialMediaConfig' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : SocialMediaConfig, 'err' : IDL.Text })],
        [],
      ),
    'getStripeCharges' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getStripeConfiguration' : IDL.Func(
        [],
        [IDL.Opt(StripeConfiguration)],
        ['query'],
      ),
    'getStripeCustomers' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getStripeDashboardData' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getStripePayouts' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getStripePublishableKey' : IDL.Func([], [IDL.Text], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getStripeSubscriptions' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getStripeTestMode' : IDL.Func([], [IDL.Bool], ['query']),
    'getSubAdmins' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Vec(IDL.Tuple(IDL.Text, SubAdmin)),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getTopPages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64))],
        ['query'],
      ),
    'getUnreadMessageCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getVapidPublicKey' : IDL.Func([], [IDL.Text], ['query']),
    'getVisitorStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'todayUnique' : IDL.Nat,
            'weekUnique' : IDL.Nat,
            'monthUnique' : IDL.Nat,
            'todaySessions' : IDL.Nat,
            'allTimeUnique' : IDL.Nat,
            'monthSessions' : IDL.Nat,
            'weekSessions' : IDL.Nat,
            'allTimeSessions' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getWebhookAuditLog' : IDL.Func([], [IDL.Vec(WebhookAuditEntry)], []),
    'handleStripeWebhook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'helpRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'initAdminAccount' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isGoogleCalendarConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isGoogleSheetsConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeTestMode' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [
          IDL.Record({
            'email' : IDL.Text,
            'passwordHash' : IDL.Vec(IDL.Nat8),
          }),
        ],
        [LoginResult],
        [],
      ),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markCompletionPaymentCharged' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'markInvoicePaid' : IDL.Func([IDL.Text, IDL.Text], [UpsertResult], []),
    'markMessagesRead' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'markQuestionnaireReviewed' : IDL.Func([QuestionnaireId], [], []),
    'publishBlogPost' : IDL.Func([BlogPostId], [], []),
    'publishPortfolioItem' : IDL.Func([IDL.Text], [UpsertResult], []),
    'recordVisit' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'registerAdminPrincipal' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'registerUser' : IDL.Func(
        [
          IDL.Record({
            'email' : IDL.Text,
            'passwordHash' : IDL.Vec(IDL.Nat8),
            'lastName' : IDL.Text,
            'firstName' : IDL.Text,
          }),
        ],
        [UpsertResult],
        [],
      ),
    'rejectReview' : IDL.Func(
        [ReviewId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeAdminPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removeFleetCanister' : IDL.Func([IDL.Text], [], []),
    'removeFleetSite' : IDL.Func([IDL.Text], [], []),
    'removeFleetSoftware' : IDL.Func([IDL.Text], [], []),
    'removeProductImage' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removePushSubscription' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'removeSubAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'reorderMarqueeLogos' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'requestAccountDeletion' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'requestPasswordReset' : IDL.Func([IDL.Text], [IDL.Text], []),
    'rescheduleEmailCampaign' : IDL.Func(
        [IDL.Nat, IDL.Int],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'rescheduleLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'reseedCatalog' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'resendEmail' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'resendSiteLink' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resetPasswordWithToken' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Text],
        [],
      ),
    'saveEmailTemplate' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'savePushSubscription' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'sendDepositInvoice' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Nat, IDL.Text, Timestamp],
        [IDL.Text],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ClientMessage, 'err' : IDL.Text })],
        [],
      ),
    'sendNowEmailCampaign' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'sendOrderStatusEmail' : IDL.Func(
        [IDL.Principal, Status, IDL.Text],
        [],
        [],
      ),
    'sendRescheduleLink' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool })],
        [],
      ),
    'sendSiteLink' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'sendUpcomingBillingReminders' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'setAdminEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setAvailability' : IDL.Func([AvailabilitySettings], [], []),
    'setClientWebhookSecret' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setGlobalTaxRate' : IDL.Func(
        [IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setGoogleCalendarConfig' : IDL.Func(
        [GoogleCalendarConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setGoogleSheetsConfig' : IDL.Func(
        [GoogleSheetsConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setLogoUrl' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setReminderLeadDays' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setSiteAuditFallbackPrice' : IDL.Func(
        [IDL.Int],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setSiteBaseUrl' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setSocialMediaConfig' : IDL.Func(
        [SocialMediaConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setStripePublishableKey' : IDL.Func([IDL.Text], [], []),
    'setStripeSecretKey' : IDL.Func([IDL.Text], [], []),
    'setStripeTestMode' : IDL.Func([IDL.Bool], [], []),
    'setStripeWebhookSecret' : IDL.Func([IDL.Text], [], []),
    'setVapidKeys' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setWebhookSharedSecret' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitCancellationRequest' : IDL.Func([IDL.Text], [UpsertResult], []),
    'submitQuestionnaire' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'submitReview' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ReviewId, 'err' : IDL.Text })],
        [],
      ),
    'togglePortalShopProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'toggleProductStatus' : IDL.Func([IDL.Text], [UpsertResult], []),
    'trackReferralClick' : IDL.Func([IDL.Text], [], []),
    'trackReferralConversion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unblockDate' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unpublishBlogPost' : IDL.Func([BlogPostId], [], []),
    'unpublishPortfolioItem' : IDL.Func([IDL.Text], [UpsertResult], []),
    'updateBlogPost' : IDL.Func(
        [
          BlogPostId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateCategoryVisibility' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [UpsertResult],
        [],
      ),
    'updateClientBriefStatus' : IDL.Func([IDL.Text], [UpsertResult], []),
    'updateClientHasAccount' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [UpsertResult],
        [],
      ),
    'updateClientMilestone' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateClientNotes' : IDL.Func([IDL.Text, IDL.Text], [UpsertResult], []),
    'updateClientPlatformFee' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateClientStatus' : IDL.Func([IDL.Text, IDL.Text], [UpsertResult], []),
    'updateClientStripeAccountId' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateEmailCampaign' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Int)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateLeadStatus' : IDL.Func([IDL.Text, IDL.Text], [UpsertResult], []),
    'updateMarqueeLogo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : MarqueeLogo, 'err' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [UpsertResult], []),
    'updatePortfolioItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [UpsertResult],
        [],
      ),
    'updateProductDescription' : IDL.Func(
        [IDL.Text, IDL.Text],
        [UpsertResult],
        [],
      ),
    'updateProductDetailContent' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [UpsertResult],
        [],
      ),
    'updateProductImage' : IDL.Func([IDL.Text, IDL.Text], [UpsertResult], []),
    'updateProductPaymentType' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateProductPlanSection' : IDL.Func(
        [ProductId, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateProductPrice' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
        ],
        [UpsertResult],
        [],
      ),
    'updateProductRichFields' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [UpsertResult],
        [],
      ),
    'updateProductSpeedyFilter' : IDL.Func(
        [ProductId, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateProfile' : IDL.Func(
        [
          IDL.Record({
            'businessName' : IDL.Text,
            'businessType' : IDL.Text,
            'email' : IDL.Text,
            'phone' : IDL.Text,
            'lastName' : IDL.Text,
            'firstName' : IDL.Text,
          }),
        ],
        [UpsertResult],
        [],
      ),
    'updateQuestionDefinitions' : IDL.Func(
        [IDL.Text, IDL.Vec(QuestionDefinition)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateSiteText' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateSubAdminTabs' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'uploadFileToClient' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ClientFileMetadata, 'err' : IDL.Text })],
        [],
      ),
    'verifyAdminOTP' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'verifyAndRecordPurchase' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'verifySession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };