/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityId = bigint;
export interface ActivityLog {
  'id' : ActivityId,
  'status_at_time' : Status,
  'description' : string,
  'created_at' : Timestamp,
  'order_id' : OrderId,
  'client_id' : ClientId,
}
export interface AdHocInvoice {
  'id' : bigint,
  'status' : string,
  'clientId' : string,
  'createdAt' : bigint,
  'dueDate' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'invoiceNumber' : string,
  'stripeSessionId' : string,
  'amount' : number,
  'paidAt' : [] | [bigint],
}
export interface AdminNotification {
  'id' : string,
  'title' : string,
  'notifType' : string,
  'read' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export interface AdminStats {
  'outstandingInvoices' : bigint,
  'activeProjects' : bigint,
  'totalClients' : bigint,
  'unreviewedQuestionnaires' : bigint,
}
export interface AvailabilitySettings {
  'timezone' : [] | [string],
  'blockedDates' : Array<string>,
  'weeklySchedule' : WeeklySchedule,
}
export interface BillingHistory {
  'id' : BillingId,
  'status' : string,
  'payment_date' : Timestamp,
  'subscription_id' : SubscriptionId,
  'description' : string,
  'created_at' : Timestamp,
  'stripe_payment_intent_id' : string,
  'client_id' : ClientId,
  'amount' : number,
}
export type BillingId = bigint;
export interface BlogPost {
  'id' : BlogPostId,
  'seoMetaKeywords' : [] | [string],
  'status' : string,
  'title' : string,
  'updated_at' : Timestamp,
  'body' : string,
  'slug' : string,
  'published_at' : [] | [Timestamp],
  'created_at' : Timestamp,
  'author' : string,
  'excerpt' : string,
  'category' : string,
  'seoMetaDescription' : [] | [string],
  'featured_image_url' : [] | [string],
  'featuredImageCaption' : string,
}
export type BlogPostId = bigint;
export interface Build {
  'id' : string,
  'thumbnailUrl' : string,
  'clientName' : string,
  'description' : string,
  'addedAt' : bigint,
  'category' : string,
  'siteUrl' : string,
}
export interface BusinessMetrics {
  'activeBookings' : bigint,
  'saasPlanStatus' : string,
  'monthlyRevenueCents' : bigint,
}
export interface ClientFileMetadata {
  'id' : string,
  'objectKey' : string,
  'clientEmail' : string,
  'fileName' : string,
  'fileLabel' : string,
  'uploaderEmail' : string,
  'uploadedAt' : bigint,
}
export type ClientId = Principal;
export interface ClientMessage {
  'id' : string,
  'body' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'receiverEmail' : string,
  'senderName' : string,
  'senderEmail' : string,
}
export interface CrmClient {
  'id' : string,
  'webhookSecret' : [] | [string],
  'hasAccount' : boolean,
  'deletionRequested' : boolean,
  'source' : string,
  'name' : string,
  'milestoneUpdatedAt' : [] | [bigint],
  'onboardingBriefId' : [] | [string],
  'created_at' : bigint,
  'briefSubmittedAt' : [] | [bigint],
  'email' : string,
  'connectedAt' : [] | [bigint],
  'stripeConnectAccountId' : [] | [string],
  'notes' : string,
  'currentMilestone' : bigint,
  'platformFeePercentage' : number,
  'projectStatus' : string,
  'deletionRequestedAt' : bigint,
  'phone' : string,
  'stripeConnectStatus' : string,
  'lastActivityAt' : [] | [bigint],
  'briefStatus' : [] | [string],
  'siteLinkLog' : Array<SiteLinkEntry>,
  'completionPaymentCharged' : boolean,
  'activeServices' : Array<string>,
}
export interface DashboardMetrics {
  'totalProducts' : bigint,
  'ordersByStatus' : Array<[string, bigint]>,
  'totalOrders' : bigint,
  'totalOrderValue' : bigint,
  'outstandingInvoices' : bigint,
  'recentActivity' : Array<string>,
  'totalClients' : bigint,
  'unreviewedQuestionnaires' : bigint,
  'totalActiveSubscriptions' : bigint,
  'totalWebsites' : bigint,
}
export interface DaySchedule {
  'endHour' : bigint,
  'isOpen' : boolean,
  'startHour' : bigint,
}
export interface EditRequest {
  'id' : EditRequestId,
  'status' : string,
  'request_type' : string,
  'updated_at' : Timestamp,
  'description' : string,
  'created_at' : Timestamp,
  'page_or_section' : string,
  'request_number' : string,
  'order_id' : [] | [OrderId],
  'client_id' : ClientId,
  'attachment_url' : [] | [string],
}
export type EditRequestId = bigint;
export interface EmailCampaign {
  'id' : EmailCampaignId,
  'status' : string,
  'subject' : string,
  'scheduledDate' : [] | [bigint],
  'body' : string,
  'createdAt' : bigint,
  'sentAt' : [] | [bigint],
  'recipients' : Array<string>,
}
export type EmailCampaignId = bigint;
export interface EmailLog {
  'id' : string,
  'status' : string,
  'templateName' : string,
  'timestamp' : bigint,
  'recipientEmail' : string,
}
export interface EmailTemplate {
  'id' : EmailTemplateId,
  'updated_at' : Timestamp,
  'subject' : string,
  'body' : string,
  'trigger_key' : string,
}
export type EmailTemplateId = bigint;
export interface FleetCanister {
  'id' : string,
  'name' : string,
  'created_at' : Timestamp,
}
export interface GoogleCalendarConfig {
  'scriptUrl' : string,
  'calendarId' : string,
  'titleTemplate' : string,
  'defaultDurationMinutes' : bigint,
}
export interface GoogleSheetsConfig { 'scriptUrl' : string, 'sheetId' : string }
export interface Invoice {
  'id' : InvoiceId,
  'status' : string,
  'updated_at' : Timestamp,
  'invoice_number' : string,
  'description' : string,
  'created_at' : Timestamp,
  'stripe_payment_intent_id' : string,
  'due_date' : Timestamp,
  'paid_at' : [] | [Timestamp],
  'order_id' : [] | [OrderId],
  'client_id' : ClientId,
  'amount' : number,
}
export type InvoiceId = bigint;
export interface Lead {
  'id' : string,
  'status' : string,
  'meetLink' : string,
  'rescheduleToken' : string,
  'convertedAt' : [] | [bigint],
  'name' : string,
  'path' : string,
  'rescheduleHistory' : Array<bigint>,
  'created_at' : Timestamp,
  'email' : string,
  'isDraft' : boolean,
  'message' : string,
  'business' : string,
  'meetingMethod' : string,
  'rescheduleLinkSentAt' : [] | [bigint],
}
export type LoginResult = {
    'ok' : { 'role' : string, 'email' : string, 'firstName' : string }
  } |
  { 'err' : string };
export interface MarqueeLogo {
  'id' : string,
  'order' : bigint,
  'logoUrl' : string,
  'addedAt' : bigint,
  'logoLabel' : string,
}
export interface NotificationLogEntry {
  'id' : string,
  'url' : string,
  'title' : string,
  'body' : string,
  'event' : string,
  'timestamp' : bigint,
}
export interface Order {
  'id' : OrderId,
  'status' : Status,
  'updated_at' : Timestamp,
  'delivery_window' : string,
  'created_at' : Timestamp,
  'launch_target' : string,
  'client_id' : ClientId,
  'amount' : number,
  'tier_code' : string,
}
export type OrderId = bigint;
export interface PendingNotification {
  'id' : string,
  'url' : string,
  'title' : string,
  'body' : string,
  'createdAt' : bigint,
}
export interface PortfolioItem {
  'id' : string,
  'seoMetaKeywords' : [] | [string],
  'client_name' : string,
  'published' : boolean,
  'description' : string,
  'created_at' : Timestamp,
  'site_url' : string,
  'thumbnail_url' : string,
  'imageCaption' : string,
  'is_featured' : boolean,
  'seoMetaDescription' : [] | [string],
  'tier_code' : string,
}
export interface Product {
  'id' : ProductId,
  'proofPoints' : [] | [string],
  'show_questionnaire' : boolean,
  'seoMetaTitle' : [] | [string],
  'faqItems' : [] | [string],
  'active' : boolean,
  'payment_type' : string,
  'price_monthly' : [] | [number],
  'speedy_filter' : [] | [string],
  'tagline' : [] | [string],
  'plan_section' : [] | [string],
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'created_at' : Timestamp,
  'closingCTA' : [] | [string],
  'bodySections' : [] | [string],
  'upgradePath' : [] | [string],
  'imageUrl' : [] | [string],
  'product_type' : string,
  'recommendedPlan' : [] | [string],
  'heroSubheadline' : [] | [string],
  'detailDescription' : [] | [string],
  'seoMetaDescription' : [] | [string],
  'featureBullets' : Array<string>,
  'heroHeadline' : [] | [string],
  'bestFor' : [] | [string],
  'video_url_1' : string,
  'video_url_2' : string,
  'price_onetime' : [] | [number],
  'tier_code' : [] | [string],
  'price_annual' : [] | [number],
}
export type ProductId = bigint;
export interface PurchaseRequest {
  'id' : bigint,
  'status' : string,
  'clientEmail' : string,
  'productId' : bigint,
  'productName' : string,
  'checkoutUrl' : [] | [string],
  'frequency' : string,
  'amount' : number,
  'declineReason' : [] | [string],
  'respondedAt' : [] | [bigint],
  'requestedAt' : bigint,
}
export interface PushSubscription {
  'endpoint' : string,
  'auth' : string,
  'p256dh' : string,
}
export interface QuestionDefinition {
  'id' : string,
  'inputType' : string,
  'questionLabel' : string,
  'tierCode' : string,
  'sortOrder' : bigint,
  'description' : string,
  'required' : boolean,
  'placeholder' : string,
  'options' : Array<string>,
}
export interface Questionnaire {
  'id' : QuestionnaireId,
  'updated_at' : Timestamp,
  'submitted' : boolean,
  'answers' : string,
  'reviewed_at' : [] | [Timestamp],
  'created_at' : Timestamp,
  'progress' : bigint,
  'order_id' : OrderId,
  'reviewed' : boolean,
  'client_id' : ClientId,
  'submitted_at' : [] | [Timestamp],
  'tier_code' : string,
}
export type QuestionnaireId = bigint;
export interface ReferralStat {
  'successfulConversions' : bigint,
  'referrerName' : string,
  'code' : string,
  'referrerEmail' : string,
  'totalClicks' : bigint,
}
export interface Review {
  'id' : ReviewId,
  'status' : string,
  'clientName' : string,
  'clientEmail' : string,
  'submittedAt' : bigint,
  'reviewText' : string,
  'jobTitle' : string,
  'rating' : bigint,
}
export type ReviewId = string;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteLinkEntry { 'url' : string, 'sentAt' : bigint }
export interface SocialMediaConfig {
  'instagramUrl' : string,
  'youtubeUrl' : string,
  'facebookUrl' : string,
  'linkedinUrl' : string,
  'tiktokUrl' : string,
}
export type Status = { 'depositReceived' : null } |
  { 'cancelled' : null } |
  { 'draftReady' : null } |
  { 'questionnaireComplete' : null } |
  { 'live' : null } |
  { 'buildInProgress' : null } |
  { 'revisionsInProgress' : null } |
  { 'questionnairePending' : null } |
  { 'launching' : null } |
  { 'paused' : null } |
  { 'depositSent' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubAdmin {
  'allowedTabs' : Array<string>,
  'createdAt' : bigint,
  'email' : string,
}
export interface Subscription {
  'id' : SubscriptionId,
  'status' : string,
  'nextBillingDate' : bigint,
  'updated_at' : Timestamp,
  'plan_code' : string,
  'plan_name' : string,
  'billing_cycle' : string,
  'clientEmail' : string,
  'created_at' : Timestamp,
  'stripeCustomerId' : [] | [string],
  'stripe_subscription_id' : string,
  'client_id' : ClientId,
  'reminderSentAt' : [] | [bigint],
  'next_payment_date' : Timestamp,
  'paymentFailed' : boolean,
}
export type SubscriptionId = bigint;
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UpsertResult = { 'ok' : null } |
  { 'err' : string } |
  { 'okAlreadyAdvanced' : null };
export interface UserProfile {
  'role' : string,
  'businessName' : string,
  'businessType' : string,
  'created_at' : Timestamp,
  'email' : string,
  'passwordHash' : Uint8Array,
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WebhookAuditEntry {
  'received_at' : bigint,
  'event_id' : string,
  'processing_result' : string,
  'event_type' : string,
}
export interface WeeklySchedule {
  'tuesday' : DaySchedule,
  'wednesday' : DaySchedule,
  'saturday' : DaySchedule,
  'thursday' : DaySchedule,
  'sunday' : DaySchedule,
  'friday' : DaySchedule,
  'monday' : DaySchedule,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'activateSubscription' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addBuild' : ActorMethod<
    [string, string, [] | [string], [] | [string], [] | [string]],
    { 'ok' : Build } |
      { 'err' : string }
  >,
  'addClient' : ActorMethod<
    [string, string, string, string, Array<string>, [] | [string]],
    string
  >,
  'addFleetCanister' : ActorMethod<[string, string], undefined>,
  'addFleetSite' : ActorMethod<[string, string], undefined>,
  'addFleetSoftware' : ActorMethod<[string, string], undefined>,
  'addMarqueeLogo' : ActorMethod<
    [string, string],
    { 'ok' : MarqueeLogo } |
      { 'err' : string }
  >,
  'addSubAdmin' : ActorMethod<
    [string, Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateClientProfile' : ActorMethod<
    [string, string, string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'approvePurchaseRequest' : ActorMethod<
    [bigint, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'approveReview' : ActorMethod<
    [ReviewId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignMeetingToLead' : ActorMethod<
    [string, string, string, string],
    { 'ok' : boolean, 'meetLink' : string }
  >,
  'blockDate' : ActorMethod<[string], undefined>,
  'cancelEmailCampaign' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'cancelSubscription' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'changePassword' : ActorMethod<
    [
      {
        'email' : string,
        'newPasswordHash' : Uint8Array,
        'currentPasswordHash' : Uint8Array,
      },
    ],
    UpsertResult
  >,
  'checkStripeSessionPaid' : ActorMethod<
    [string],
    { 'notPaid' : null } |
      { 'paid' : null } |
      { 'error' : string }
  >,
  'clearGoogleCalendarConfig' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'clearGoogleSheetsConfig' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'clearNotificationLog' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'clearPendingPushNotifications' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'convertLeadToClient' : ActorMethod<
    [string, string, string, string, string, Array<string>, [] | [string]],
    string
  >,
  'createAdHocInvoiceSession' : ActorMethod<
    [string, string, bigint, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createBlogPost' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      [] | [string],
      [] | [string],
    ],
    UpsertResult
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createCompletionPaymentSession' : ActorMethod<
    [string, string, string],
    string
  >,
  'createDraftLead' : ActorMethod<
    [string, string, string, string],
    { 'ok' : boolean, 'leadId' : string }
  >,
  'createEditRequest' : ActorMethod<
    [string, string, string, string],
    UpsertResult
  >,
  'createEmailCampaign' : ActorMethod<
    [string, string, Array<string>, [] | [bigint]],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'createLead' : ActorMethod<[string, string, string, string, string], string>,
  'createPortfolioItem' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
      [] | [string],
      [] | [string],
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [string],
      Array<string>,
      [] | [string],
      [] | [string],
      [] | [string],
      string,
      string,
      string,
      boolean,
      [] | [string],
      [] | [string],
    ],
    { 'ok' : ProductId } |
      { 'err' : string }
  >,
  'createPurchaseRequest' : ActorMethod<
    [string, bigint, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createStripePaymentSession' : ActorMethod<
    [string, bigint, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createStripePortalSession' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'declinePurchaseRequest' : ActorMethod<
    [bigint, [] | [string]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteBlogPost' : ActorMethod<[BlogPostId], undefined>,
  'deleteBuild' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteClient' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'deleteClientFile' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteLead' : ActorMethod<[string], undefined>,
  'deleteMarqueeLogo' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deletePortfolioItem' : ActorMethod<[string], UpsertResult>,
  'deleteProduct' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'deleteQuestionnaire' : ActorMethod<[QuestionnaireId], undefined>,
  'deleteReferral' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteReview' : ActorMethod<
    [ReviewId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'editBuild' : ActorMethod<
    [string, string, string, [] | [string], [] | [string], [] | [string]],
    { 'ok' : Build } |
      { 'err' : string }
  >,
  'generateAdminOTP' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'generatePartnerLink' : ActorMethod<[string, string], string>,
  'getAdHocClientInvoices' : ActorMethod<[string], Array<AdHocInvoice>>,
  'getAdminAllActivity' : ActorMethod<[], Array<ActivityLog>>,
  'getAdminAllClients' : ActorMethod<[], Array<UserProfile>>,
  'getAdminAllOrders' : ActorMethod<[], Array<Order>>,
  'getAdminAllQuestionnaires' : ActorMethod<[], Array<Questionnaire>>,
  'getAdminBillingHistory' : ActorMethod<
    [],
    { 'ok' : Array<BillingHistory> } |
      { 'err' : string }
  >,
  'getAdminContactEmail' : ActorMethod<[], string>,
  'getAdminNotifications' : ActorMethod<[], Array<AdminNotification>>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllBlogPostsAdmin' : ActorMethod<[], Array<BlogPost>>,
  'getAllEmailCampaigns' : ActorMethod<
    [],
    { 'ok' : Array<EmailCampaign> } |
      { 'err' : string }
  >,
  'getAllPortfolioAdmin' : ActorMethod<[], Array<PortfolioItem>>,
  'getAllProductsAdmin' : ActorMethod<[], Array<Product>>,
  'getAllSiteText' : ActorMethod<[], Array<[string, string]>>,
  'getApprovedReviews' : ActorMethod<[], Array<Review>>,
  'getAvailability' : ActorMethod<[], AvailabilitySettings>,
  'getBlogPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getBuilds' : ActorMethod<[], Array<Build>>,
  'getBusinessMetrics' : ActorMethod<[], BusinessMetrics>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterCycles' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'getCategoryVisibility' : ActorMethod<[], Array<[string, boolean]>>,
  'getClientBriefStatus' : ActorMethod<[string], [] | [string]>,
  'getClientBusinessMetrics' : ActorMethod<
    [string],
    { 'ok' : BusinessMetrics } |
      { 'err' : string }
  >,
  'getClientByEmail' : ActorMethod<[string], [] | [CrmClient]>,
  'getClientByPrincipal' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getClientFileUrl' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getClientInvoices' : ActorMethod<[Principal], Array<Invoice>>,
  'getClientMilestone' : ActorMethod<
    [string],
    { 'ok' : [] | [bigint] } |
      { 'err' : string }
  >,
  'getClientOrderVolumes' : ActorMethod<[], Array<[string, number]>>,
  'getClientOrders' : ActorMethod<[Principal], Array<Order>>,
  'getClientPurchaseRequests' : ActorMethod<[string], Array<PurchaseRequest>>,
  'getClients' : ActorMethod<[], Array<CrmClient>>,
  'getConnectedClients' : ActorMethod<[], Array<CrmClient>>,
  'getConversionStats' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    {
      'convertedLeads' : bigint,
      'totalLeads' : bigint,
      'conversionRate' : number,
    }
  >,
  'getCountryBreakdown' : ActorMethod<[], Array<[string, bigint, number]>>,
  'getCycles' : ActorMethod<[], bigint>,
  'getDailyVisitorChart' : ActorMethod<[], Array<[string, bigint]>>,
  'getDashboardMetrics' : ActorMethod<[], DashboardMetrics>,
  'getEmailHealth' : ActorMethod<
    [],
    {
      'totalFailures' : bigint,
      'lastFailureTimestamp' : bigint,
      'last24hFailures' : bigint,
    }
  >,
  'getEmailLogs' : ActorMethod<[], Array<EmailLog>>,
  'getEmailTemplates' : ActorMethod<[], Array<EmailTemplate>>,
  'getFilesForClient' : ActorMethod<
    [string, string],
    Array<ClientFileMetadata>
  >,
  'getFleetSites' : ActorMethod<[], Array<FleetCanister>>,
  'getFleetSoftware' : ActorMethod<[], Array<FleetCanister>>,
  'getGlobalTaxRate' : ActorMethod<[], number>,
  'getGoogleCalendarConfig' : ActorMethod<
    [],
    { 'ok' : GoogleCalendarConfig } |
      { 'err' : string }
  >,
  'getGoogleSheetsConfig' : ActorMethod<
    [],
    { 'ok' : GoogleSheetsConfig } |
      { 'err' : string }
  >,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getLiveVisitorCount' : ActorMethod<[], bigint>,
  'getLogoUrl' : ActorMethod<[], string>,
  'getMarqueeLogos' : ActorMethod<[], Array<MarqueeLogo>>,
  'getMessages' : ActorMethod<[string, string], Array<ClientMessage>>,
  'getMyActivity' : ActorMethod<[], Array<ActivityLog>>,
  'getMyAdHocInvoices' : ActorMethod<[], Array<AdHocInvoice>>,
  'getMyAdminPermissions' : ActorMethod<
    [],
    { 'ok' : Array<string> } |
      { 'err' : string }
  >,
  'getMyBillingHistory' : ActorMethod<[], Array<BillingHistory>>,
  'getMyEditRequests' : ActorMethod<[], Array<EditRequest>>,
  'getMyInvoices' : ActorMethod<[], Array<Invoice>>,
  'getMyMostRecentQuestionnaire' : ActorMethod<[], [] | [Questionnaire]>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getMyQuestionnaires' : ActorMethod<[], Array<Questionnaire>>,
  'getMyReferralClicks' : ActorMethod<[], bigint>,
  'getMyReferralCode' : ActorMethod<[string], [] | [string]>,
  'getMyReferralConversions' : ActorMethod<[string], bigint>,
  'getMyReview' : ActorMethod<[string], [] | [Review]>,
  'getMySubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getNextAvailableSlot' : ActorMethod<
    [],
    { 'date' : string, 'time' : string }
  >,
  'getNotificationLog' : ActorMethod<
    [],
    { 'ok' : Array<NotificationLogEntry> } |
      { 'err' : string }
  >,
  'getOrCreateMyReferralCode' : ActorMethod<[], string>,
  'getPendingPushNotifications' : ActorMethod<
    [],
    { 'ok' : Array<PendingNotification> } |
      { 'err' : string }
  >,
  'getPendingReviews' : ActorMethod<[], Array<Review>>,
  'getPendingSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getPortalShopProductIds' : ActorMethod<[], Array<bigint>>,
  'getPortalShopProducts' : ActorMethod<[], Array<Product>>,
  'getProductImageUrl' : ActorMethod<[bigint], [] | [string]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByType' : ActorMethod<[string], Array<Product>>,
  'getPublicAvailability' : ActorMethod<[], AvailabilitySettings>,
  'getPublicBuilds' : ActorMethod<[], Array<Build>>,
  'getPublicBuildsCount' : ActorMethod<[], bigint>,
  'getPublicSocialMediaConfig' : ActorMethod<[], SocialMediaConfig>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getPublishedPortfolio' : ActorMethod<[], Array<PortfolioItem>>,
  'getPurchaseRequests' : ActorMethod<
    [],
    { 'ok' : Array<PurchaseRequest> } |
      { 'err' : string }
  >,
  'getPushSubscription' : ActorMethod<
    [],
    { 'ok' : [] | [PushSubscription] } |
      { 'err' : string }
  >,
  'getQuestionDefinitions' : ActorMethod<[string], Array<QuestionDefinition>>,
  'getQuestionnaireByClientId' : ActorMethod<[ClientId], [] | [Questionnaire]>,
  'getReferralStats' : ActorMethod<[], Array<ReferralStat>>,
  'getRejectedReviews' : ActorMethod<[], Array<Review>>,
  'getReminderLeadDays' : ActorMethod<[], bigint>,
  'getRescheduleHistory' : ActorMethod<[string], Array<bigint>>,
  'getRescheduleLeadByToken' : ActorMethod<
    [string],
    [] | [{ 'isExpired' : boolean, 'lead' : Lead }]
  >,
  'getSiteBaseUrl' : ActorMethod<[], string>,
  'getSiteLinkLog' : ActorMethod<
    [string],
    { 'ok' : Array<SiteLinkEntry> } |
      { 'err' : string }
  >,
  'getSiteText' : ActorMethod<[string], [] | [string]>,
  'getSocialMediaConfig' : ActorMethod<
    [],
    { 'ok' : SocialMediaConfig } |
      { 'err' : string }
  >,
  'getStripeCharges' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'getStripeConfiguration' : ActorMethod<[], [] | [StripeConfiguration]>,
  'getStripeCustomers' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getStripeDashboardData' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getStripePayouts' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'getStripePublishableKey' : ActorMethod<[], string>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getStripeSubscriptions' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getStripeTestMode' : ActorMethod<[], boolean>,
  'getSubAdmins' : ActorMethod<
    [],
    { 'ok' : Array<[string, SubAdmin]> } |
      { 'err' : string }
  >,
  'getTopPages' : ActorMethod<[], Array<[string, bigint, number]>>,
  'getUnreadMessageCounts' : ActorMethod<[], Array<[string, bigint]>>,
  'getVapidPublicKey' : ActorMethod<[], string>,
  'getVisitorStats' : ActorMethod<
    [],
    {
      'todayUnique' : bigint,
      'weekUnique' : bigint,
      'monthUnique' : bigint,
      'todaySessions' : bigint,
      'allTimeUnique' : bigint,
      'monthSessions' : bigint,
      'weekSessions' : bigint,
      'allTimeSessions' : bigint,
    }
  >,
  'getWebhookAuditLog' : ActorMethod<[], Array<WebhookAuditEntry>>,
  'handleStripeWebhook' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'helpRequest' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'initAdminAccount' : ActorMethod<[string, Uint8Array], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isGoogleCalendarConfigured' : ActorMethod<[], boolean>,
  'isGoogleSheetsConfigured' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isStripeTestMode' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [{ 'email' : string, 'passwordHash' : Uint8Array }],
    LoginResult
  >,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markCompletionPaymentCharged' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'markInvoicePaid' : ActorMethod<[string, string], UpsertResult>,
  'markMessagesRead' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'markQuestionnaireReviewed' : ActorMethod<[QuestionnaireId], undefined>,
  'publishBlogPost' : ActorMethod<[BlogPostId], undefined>,
  'publishPortfolioItem' : ActorMethod<[string], UpsertResult>,
  'recordVisit' : ActorMethod<[string, bigint, string, [] | [string]], boolean>,
  'registerAdminPrincipal' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<
    [
      {
        'email' : string,
        'passwordHash' : Uint8Array,
        'lastName' : string,
        'firstName' : string,
      },
    ],
    UpsertResult
  >,
  'rejectReview' : ActorMethod<
    [ReviewId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeAdminPrincipal' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeFleetCanister' : ActorMethod<[string], undefined>,
  'removeFleetSite' : ActorMethod<[string], undefined>,
  'removeFleetSoftware' : ActorMethod<[string], undefined>,
  'removeProductImage' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removePushSubscription' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'removeSubAdmin' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'reorderMarqueeLogos' : ActorMethod<
    [Array<string>],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'requestAccountDeletion' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'requestPasswordReset' : ActorMethod<[string], string>,
  'rescheduleEmailCampaign' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'rescheduleLead' : ActorMethod<
    [string, string, string, string],
    { 'ok' : boolean, 'message' : string }
  >,
  'reseedCatalog' : ActorMethod<[], { 'ok' : string } | { 'err' : string }>,
  'resendEmail' : ActorMethod<[string, string], boolean>,
  'resendSiteLink' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resetPasswordWithToken' : ActorMethod<[string, Uint8Array], string>,
  'saveEmailTemplate' : ActorMethod<[string, string, string], undefined>,
  'savePushSubscription' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'sendDepositInvoice' : ActorMethod<
    [Principal, string, bigint, string, Timestamp],
    string
  >,
  'sendMessage' : ActorMethod<
    [string, string, string],
    { 'ok' : ClientMessage } |
      { 'err' : string }
  >,
  'sendNowEmailCampaign' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendOrderStatusEmail' : ActorMethod<[Principal, Status, string], undefined>,
  'sendRescheduleLink' : ActorMethod<
    [string],
    { 'message' : string, 'success' : boolean }
  >,
  'sendSiteLink' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'sendUpcomingBillingReminders' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'setAdminEmail' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'setAvailability' : ActorMethod<[AvailabilitySettings], undefined>,
  'setClientWebhookSecret' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setGlobalTaxRate' : ActorMethod<
    [number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setGoogleCalendarConfig' : ActorMethod<
    [GoogleCalendarConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setGoogleSheetsConfig' : ActorMethod<
    [GoogleSheetsConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setLogoUrl' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'setReminderLeadDays' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSiteAuditFallbackPrice' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSiteBaseUrl' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setSocialMediaConfig' : ActorMethod<
    [SocialMediaConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setStripePublishableKey' : ActorMethod<[string], undefined>,
  'setStripeSecretKey' : ActorMethod<[string], undefined>,
  'setStripeTestMode' : ActorMethod<[boolean], undefined>,
  'setStripeWebhookSecret' : ActorMethod<[string], undefined>,
  'setVapidKeys' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setWebhookSharedSecret' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitCancellationRequest' : ActorMethod<[string], UpsertResult>,
  'submitQuestionnaire' : ActorMethod<[string, string], bigint>,
  'submitReview' : ActorMethod<
    [string, bigint, string, string],
    { 'ok' : ReviewId } |
      { 'err' : string }
  >,
  'togglePortalShopProduct' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'toggleProductStatus' : ActorMethod<[string], UpsertResult>,
  'trackReferralClick' : ActorMethod<[string], undefined>,
  'trackReferralConversion' : ActorMethod<[string, string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unblockDate' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'unpublishBlogPost' : ActorMethod<[BlogPostId], undefined>,
  'unpublishPortfolioItem' : ActorMethod<[string], UpsertResult>,
  'updateBlogPost' : ActorMethod<
    [
      BlogPostId,
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updateCategoryVisibility' : ActorMethod<[string, boolean], UpsertResult>,
  'updateClientBriefStatus' : ActorMethod<[string], UpsertResult>,
  'updateClientHasAccount' : ActorMethod<[string, boolean], UpsertResult>,
  'updateClientMilestone' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateClientNotes' : ActorMethod<[string, string], UpsertResult>,
  'updateClientPlatformFee' : ActorMethod<
    [string, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateClientStatus' : ActorMethod<[string, string], UpsertResult>,
  'updateClientStripeAccountId' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateEmailCampaign' : ActorMethod<
    [bigint, string, string, Array<string>, [] | [bigint]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateLeadStatus' : ActorMethod<[string, string], UpsertResult>,
  'updateMarqueeLogo' : ActorMethod<
    [string, string, string],
    { 'ok' : MarqueeLogo } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<[string, string], UpsertResult>,
  'updatePortfolioItem' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
      [] | [string],
      [] | [string],
    ],
    UpsertResult
  >,
  'updateProductDescription' : ActorMethod<[string, string], UpsertResult>,
  'updateProductDetailContent' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    UpsertResult
  >,
  'updateProductImage' : ActorMethod<[string, string], UpsertResult>,
  'updateProductPaymentType' : ActorMethod<[string, string], boolean>,
  'updateProductPlanSection' : ActorMethod<
    [ProductId, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProductPrice' : ActorMethod<
    [string, [] | [number], [] | [number], [] | [number]],
    UpsertResult
  >,
  'updateProductRichFields' : ActorMethod<
    [
      string,
      [] | [string],
      Array<string>,
      [] | [string],
      [] | [string],
      [] | [string],
      string,
      string,
      boolean,
    ],
    UpsertResult
  >,
  'updateProductSpeedyFilter' : ActorMethod<
    [ProductId, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProfile' : ActorMethod<
    [
      {
        'businessName' : string,
        'businessType' : string,
        'email' : string,
        'phone' : string,
        'lastName' : string,
        'firstName' : string,
      },
    ],
    UpsertResult
  >,
  'updateQuestionDefinitions' : ActorMethod<
    [string, Array<QuestionDefinition>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateSiteText' : ActorMethod<[string, string], boolean>,
  'updateSubAdminTabs' : ActorMethod<
    [string, Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'uploadFileToClient' : ActorMethod<
    [string, Uint8Array, string, string],
    { 'ok' : ClientFileMetadata } |
      { 'err' : string }
  >,
  'verifyAdminOTP' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'verifyAndRecordPurchase' : ActorMethod<
    [string, string, string, Array<string>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'verifySession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];