export const ADMIN_TABS: string[] = [
  "Dashboard",
  "Analytics",
  "Clients",
  "Questionnaires",
  "Leads",
  "Referrals",
  "Orders",
  "Stripe Settings",
  "Platform",
  "Spreadsheet",
  "Reviews",
  "Services",
  "Builds",
  "Annual Revenue",
  "Portfolio",
  "Blog",
  "Bulk Email",
  "Email Templates",
  "Email Logs",
  "Site Text",
  "Notification Log",
  "Push Settings",
  "Google Calendar",
  "Social Media",
  "Fleet",
  "Profile",
];
